// src/components/NavButtons.tsx
import type { I18n } from "../lib/i18n";

export function NavButtons({ i18n }: { i18n: I18n }) {
  const links = [
    { href: "#experience", key: "page.experience.nav" },
    { href: "#projects", key: "page.projects.nav" },
    { href: "#skills", key: "page.skills.nav" },
    { href: "#contact", key: "page.contact.nav" },
  ];

  return (
    <>
      {links.map((link) => (
        <li key={link.href}>
          <a href={link.href}>{i18n.t(link.key)}</a>
        </li>
      ))}
    </>
  );
}

// src/lib/components/NavButtons.svelte
<script lang="ts">
    import { i18n } from "$lib/localization.svelte";
</script>

<li><a href="/">{$i18n.t('page.home.nav')}</a></li>
<li><a href="#about">{$i18n.t('page.about.nav')}</a></li>
<li><a href="#experience">{$i18n.t('page.experience.nav')}</a></li>
<li><a href="#projects">{$i18n.t('page.projects.nav')}</a></li>
<li><a href="#contact-me">{$i18n.t('page.contact.nav')}</a></li>
